# Generated by Django 2.1.5 on 2019-04-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramUser',
            new_name='User',
        ),
    ]
