# Generated by Django 2.1.5 on 2019-04-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_auto_20190425_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='send_from',
            new_name='push_type',
        ),
    ]
