# Generated by Django 2.1.5 on 2019-04-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_auto_20190425_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='push_status',
            field=models.IntegerField(default=1),
        ),
    ]
