# Generated by Django 2.1.5 on 2019-04-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0005_auto_20190426_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=192),
        ),
        migrations.AlterField(
            model_name='user',
            name='push_token',
            field=models.CharField(blank=True, max_length=192),
        ),
    ]
