# Generated by Django 2.1.5 on 2019-04-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0006_auto_20190426_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='push_token',
            field=models.CharField(max_length=192),
        ),
    ]
